#执行peer1的配置信息
spring:
  profiles: eureka1
  application:
    name: shop-eureka-server1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除时间间隔,单位:毫秒
---
#执行peer2的配置信息
spring:
  profiles: eureka2
  application:
    name: shop-eureka-server2
server:
  port: 8762
  eureka:
    instance:
      hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除时间间隔,单位:毫秒